FROM mcr.microsoft.com/mssql/server:2022-latest

# Create environment variables
ENV ACCEPT_EULA=Y
ENV SA_PASSWORD=$SA_PASSWORD
ENV MSSQL_PID=Express

# Expose port
EXPOSE 1433

# Health check
HEALTHCHECK --interval=30s --timeout=10s --start-period=60s --retries=5 \
    CMD /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P $SA_PASSWORD -Q 'SELECT 1'

# Start SQL Server
CMD ["/opt/mssql/bin/mssql-conf", "start"]
