services:
  # Web API Service
  - type: web
    name: quantitymeasurement-api
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    healthCheckPath: /health
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://+:80
      - key: ConnectionStrings__DefaultConnection
        value: postgresql://quantity_measurement_db_zl98_user:uDtWauL3ZY25yRk3GxXTE4cFXQJ1dRE2@dpg-d7gsescvikkc7380mlog-a/quantity_measurement_db_zl98
      - key: ConnectionStrings__Redis
        value: equipped-kite-73194.upstash.io:6379,password=gQAAAAAAAR3qAAIncDI2YzZiMjkzODliYzU0NGUzYjFiYTY2MTVjN2NmMDRhNnAyNzMxOTQ,ssl=True,abortConnect=False
      - key: JwtSettings__Key
        value: ThisIsASecretKeyForJWTTokenGeneration123!@#
      - key: JwtSettings__Issuer
        value: QuantityMeasurementAPI
      - key: JwtSettings__Audience
        value: QuantityMeasurementUsers
      - key: JwtSettings__ExpirationMinutes
        value: 60
      - key: EncryptionSettings__Key
        value: ThisIsSecret32ByteKeyForEncrypt!
